Fix subprocessing in safe_mode.
Running a test in isolation fails with error:

> PHPUnit_Framework_Exception: sh: /usr/local/bin/php': No such file or directory

Due to:

```
proc_open("'/usr/local/bin/php' --some Option")
```

Proc open works differently in safemode. The quotes around the bin,
originating from `escapeshellarg`, cause failure. Remove the quotes, all
works.  No idea why. Safe_mode is baffling.